### ISSUE TITLE
Invalid path with svg's width / height equal to 1px 

### ISSUE THREAD

**Issue by Ni55aN** [retejs/connection-plugin#7]

**Comment by Ni55aN** [comment]
In local .html a path correctly positioned, but on Codepen or JSFiddle when SVG has a width or height = 1px it's offset or scaled

Quick fix: 
```css
svg.connection {
  width: 12px;
  height: 12px;
}
```
